---
- name: "Begin {{ role_name }}/tasks/custom/pgpass_file.yml"
  debug:
    msg: "Begin {{ role_name }}/tasks/custom/pgpass_file.yml"

- name: Create or update ~/.pgpass for each user
  ansible.builtin.template:
    src: pgpass.j2
    dest: "~{{ item.linux_user }}/.pgpass"
    owner: "{{ item.linux_user }}"
    group: "{{ item.linux_user }}"
    mode: "0600"
  vars:
    current_linux_user: "{{ item.linux_user }}"
  loop: "{{ pgpass_entries }}"
  no_log: true

- name: Set SELinux context for .pgpass (RHEL/CentOS only)
  ansible.builtin.command:
    cmd: "chcon -t postgresql_auth_t ~{{ item.linux_user }}/.pgpass"
  loop: "{{ pgpass_entries }}"
  when:
    - ansible_selinux is defined
    - ansible_selinux.status == "enabled"
    - ansible_selinux.mode == "enforcing"

- name: "End {{ role_name }}/tasks/custom/pgpass_file.yml"
  debug:
    msg: "End {{ role_name }}/tasks/custom/pgpass_file.yml"