---
- name: Perform multi datacenter cluster failover
  hosts: all
  become: true
  become_user: root
  remote_user: ansible
  gather_facts: false
  vars:
    # ansible_become_flags: "-H -S"
  vars_files:
    - sensitive-values
    - vars/dba_vars.yml
  collections:
    - community.postgresql

  pre_tasks:
    - name: Starting Playbook Execution
      debug:
        msg: "🚀 Starting PostgreSQL Cluster promotion!"

  roles:
    - role: multi_dc_failover
      # when: ansible_host in groups['redhat']

  post_tasks:
    - name: Playbook Execution Completed
      debug:
        msg: "✅ Multi datacenter cluster failover completed successfully!"

# ansible-playbook -i hosts__multi_datacenter.yml playbook-multi-dc-failover.yml --vault-password-file=vault-pass

# ansible dc1_leader -i hosts__multi_datacenter.yml -u ansible -b -m shell -a "patronictl -c /etc/patroni/patroni.yml list"
# ansible dc2_leader -i hosts__multi_datacenter.yml -u ansible -b -m shell -a "patronictl -c /etc/patroni/patroni.yml list"

# sudo su - postgres
# psql -c 'create database pgbench with owner postgres;'
# pgbench -d pgbench -i
# pgbench -d pgbench -T 300 -c 6 -P 5



