---
- name: Get Patroni cluster state
  ansible.builtin.shell: |
    patronictl -c /etc/patroni/patroni.yml list
  become_user: postgres
  register: patronictl_output
  changed_when: false
  ignore_errors: true

- name: Display Patroni cluster state
  ansible.builtin.debug:
    var: patronictl_output.stdout_lines
