---
- name: Configure {{ postgresql_home_dir }}/.pgpass
  become_user: postgres
  ansible.builtin.copy:
    content: |
      {% for entry in postgresql_pgpass %}
      {{ entry }}
      {% endfor %}
    dest: "{{ postgresql_home_dir }}/.pgpass"
    owner: postgres
    group: postgres
    mode: "0600"
  when:
    - postgresql_pgpass is defined
    - postgresql_pgpass | length > 0
