---
# - name: Ensure UFW is installed
#   ansible.builtin.package:
#     name: ufw
#     state: present
#     update_cache: yes

- name: Enable UFW firewall
  ansible.builtin.command: ufw --force enable
  become: yes

- name: Open PostgreSQL port in ufw
  community.general.ufw:
    port: '{{ postgresql_port }}'
    proto: tcp
    rule: allow

- name: Open Consul port in ufw
  community.general.ufw:
    port: '8301'
    proto: tcp
    rule: allow

- name: Open Patroni REST API port in ufw
  community.general.ufw:
    port: '8008'
    proto: tcp
    rule: allow

- name: Open port 9194 in ufw
  community.general.ufw:
    port: '9194'
    proto: tcp
    rule: allow

- name: Open port 8600 in ufw
  community.general.ufw:
    port: '8600'
    proto: tcp
    rule: allow

- name: Open port 8500 in ufw
  community.general.ufw:
    port: '8500'
    proto: tcp
    rule: allow

- name: Open port 8501 in ufw
  community.general.ufw:
    port: '8501'
    proto: tcp
    rule: allow

- name: Open port 8502 in ufw
  community.general.ufw:
    port: '8502'
    proto: tcp
    rule: allow

- name: Open port 8503 in ufw
  community.general.ufw:
    port: '8503'
    proto: tcp
    rule: allow


