all:
  children:
    leader:
      hosts:
        pg1:
          ansible_host: "127.0.0.1"
          ansible_port: 2221
          ip: "172.18.0.11"   # Container IP on lab-network

    replica:
      hosts:
        pg2:
          ansible_host: "127.0.0.1"
          ansible_port: 2222
          ip: "172.18.0.12"
        pg3:
          ansible_host: "127.0.0.1"
          ansible_port: 2223
          ip: "172.18.0.13"
          patroni_tag_nosync: true   # never elected Sync Standby; pg2 holds that role

    standby:
      hosts:
        pg4:
          ansible_host: "127.0.0.1"
          ansible_port: 2224
          ip: "172.18.0.14"
          patroni_standby_cluster:
            host: "172.18.0.11"   # Primary cluster leader (pg1 or pg2)
            port: 5432

  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: "~/.ssh/id_ed25519"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_python_interpreter: /usr/bin/python3
