---
- name: Deploy PostgreSQL
  hosts: all
  become: true
  become_user: root
  remote_user: ansible
  gather_facts: true
  vars:
    # ansible_become_flags: "-H -S"
  vars_files:
    - sensitive-values
    - vars/dba_vars.yml
  collections:
    - community.postgresql

  pre_tasks:
    - name: Starting Playbook Execution
      debug:
        msg: "🚀 Starting PostgreSQL installation and configuration!"

  roles:
    - role: install_postgresql_on_ubuntu
      when: ansible_host in groups['debian']

    - role: install_postgresql_on_redhat
      when: ansible_host in groups['redhat']


  post_tasks:
    - name: Playbook Execution Completed
      debug:
        msg: "✅ PostgreSQL installation and configuration completed successfully!"

# export ANSIBLE_FORCE_COLOR=1 
# ansible-playbook -i hosts.yml playbook-install-postgresql.yml --vault-password-file=vault-pass 2>&1 | tee logs/playbook-install-postgresql.yml.log

