---
- name: "Begin {{ role_name }}/tasks/custom/configure_pgsql_bin_path.yml"
  debug:
    msg: "Begin {{ role_name }}/tasks/custom/configure_pgsql_bin_path.yml"

- name: Check if PostgreSQL bin directory exists
  stat:
    path: "{{ pg_bin_path }}"
  register: pg_bin_dir

- name: Create profile script for PostgreSQL PATH
  copy:
    content: |
      # Add PostgreSQL binaries to PATH
      export PATH={{ pg_bin_path }}:$PATH
    dest: /etc/profile.d/postgresql.sh
    mode: '0755'
    owner: root
    group: root
  when: pg_bin_dir.stat.exists

- name: Source the profile script for current session
  shell: source /etc/profile.d/postgresql.sh
  args:
    executable: /bin/bash
  when: pg_bin_dir.stat.exists

- name: Verify psql is now accessible
  command: which psql
  register: psql_location
  changed_when: false
  failed_when: false

- name: Display psql location
  debug:
    msg: "psql found at: {{ psql_location.stdout }}"
  when: psql_location.rc == 0

- name: "End {{ role_name }}/tasks/custom/configure_pgsql_bin_path.yml"
  debug:
    msg: "End {{ role_name }}/tasks/custom/configure_pgsql_bin_path.yml"